[project]
name = "pynoidle"
version = "2.0.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "keyboard>=0.13.5",
    "pillow>=12.0.0",
    "pystray>=0.19.5",
]
